Task.Manager/Task.Manager.WebAdmin/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using Task.Manager.DTO;

namespace Task.Manager.WebAdmin.Controllers
{
    public class CommentsController : Controller
    {
        private string baseUrl = "https://localhost:44358/";

        [HttpGet]
        public async Task<IActionResult> Edit(int id, int assignmentId, int workerId)
        {
            using (var client = new HttpClient())
            {
                //Assignment
                var commentsUrl = $"{baseUrl}api/comments/{id}";
                var commentsResponse = await client.GetStringAsync(commentsUrl);
                var comments = JsonConvert.DeserializeObject<CommentDto>(commentsResponse);


                var assignments = deserializeAssignmentDtos(client);
                var assignment = new List<AssignmentDto>();
                assignment.Add(assignments.Result.FirstOrDefault(x => x.AssignmentId == assignmentId));
                ViewBag.Assignments = new SelectList(assignment, "AssignmentId", "Title");

                var workers = deserializeWorkerDtos(client);
                var worker = new List<WorkerDto>();
                worker.Add(workers.Result.FirstOrDefault(x => x.WorkerId == workerId));
                ViewBag.Workers = new SelectList(worker, "WorkerId", "Name");

                return View(comments);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CommentDto commentDto)
        {
            using (var client = new HttpClient())
            {
                commentDto.AddedOn=DateTime.Now;
                var commentsUrl = $"{baseUrl}api/comments/{commentDto.CommentId}";
                var commentDtoString = JsonConvert.SerializeObject(commentDto);
                var commentsResponse = await client.PutAsync(commentsUrl, new StringContent(commentDtoString, Encoding.UTF8, "application/json"));

                if (commentsResponse.IsSuccessStatusCode)
                {
                    commentDto =
                        JsonConvert.DeserializeObject<CommentDto>(
                            await commentsResponse.Content.ReadAsStringAsync());
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Update failed");
                }

                return RedirectToAction("Index","Projects");
            }
        }

        [HttpGet]
        public async Task<IActionResult> Create(int assignmentId, int projectId)
        {
            using (var client = new HttpClient())
            {
                var assignments = deserializeAssignmentDtos(client);
                var assignment = new List<AssignmentDto>();
                assignment.Add(assignments.Result.FirstOrDefault(x=>x.AssignmentId== assignmentId));
                ViewBag.Assignments = new SelectList(assignment, "AssignmentId", "Title");
                
                var projects = deserializeProjectDtos(client);
                var workers=new List<WorkerDto>();
                var project = projects.Result.FirstOrDefault(x => x.ProjectId == projectId);
                workers.AddRange(project.Workers);
                ViewBag.Workers = new SelectList(workers, "WorkerId", "Name");
                
                return View(new CommentDto());
            }
        }

        [HttpPost]
        //POST: Comments
        public async Task<IActionResult> Create(CommentDto commentDto)
        {
            using (var client = new HttpClient())
            {
                commentDto.AddedOn=DateTime.Now;
                var commentUrl = $"{baseUrl}api/comments/";
                var commentDtoString = JsonConvert.SerializeObject(commentDto);
                var commentResponse = await client.PostAsync(commentUrl,
                    new StringContent(commentDtoString, Encoding.UTF8, "application/json"));
                var id = commentDto.AssignmentId;
                if (commentResponse.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index", "Projects");

                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Update failed");
                    return View(commentDto);
                }
            }
        }
        public async Task<IActionResult> Delete(int id)
        {
            using (var client = new HttpClient())
            {
                var commentUrl = $"{baseUrl}api/comments/{id}";
                var commentsResponse = await client.DeleteAsync(commentUrl);

                var result = commentsResponse;
                if (result.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index","Projects");
                }
            }

            return RedirectToAction("Index", "Projects");
        }

        private async Task<List<AssignmentDto>> deserializeAssignmentDtos(HttpClient client)
        {
            var assignmentsUrl = $"{baseUrl}api/assignments";
            var assignmentsResponse = await client.GetStringAsync(assignmentsUrl);
            var assignments = JsonConvert.DeserializeObject<List<AssignmentDto>>(assignmentsResponse);
            
            return assignments;
        }

        private async Task<List<WorkerDto>> deserializeWorkerDtos(HttpClient client)
        {
            var workersUrl = $"{baseUrl}api/workers";
            var workersResponse = await client.GetStringAsync(workersUrl);
            var workers = JsonConvert.DeserializeObject<List<WorkerDto>>(workersResponse);
            
            return workers;
        }

        private async Task<List<ProjectDto>> deserializeProjectDtos(HttpClient client)
        {
            var projectsUrl = $"{baseUrl}api/projects";
            var projectsResponse = await client.GetStringAsync(projectsUrl);
            var projects = JsonConvert.DeserializeObject<List<ProjectDto>>(projectsResponse);
            return projects;
        }
    }
}

Task.Manager/Task.Manager.WebAdmin/Controllers/WorkersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using Task.Manager.DTO;
using Task.Manager.Entities;

namespace Task.Manager.WebAdmin.Controllers
{
    public class WorkersController : Controller
    {
        private string baseUrl = "https://localhost:44358/";

        public async Task<IActionResult> Index()
        {
            using (var client = new HttpClient())
            {
                var workersUrl = $"{baseUrl}api/workers";
                var workersResponse = await client.GetStringAsync(workersUrl);

                var workers = JsonConvert.DeserializeObject<List<WorkerDto>>(workersResponse);

                return View(workers);
            }
        }

        public async Task<IActionResult> Get(int id)
        {
            using (var client = new HttpClient())
            {
                //Workers
                var workersUrl = $"{baseUrl}api/workers/{id}";
                var workersResponse = await client.GetStringAsync(workersUrl);
                var worker = JsonConvert.DeserializeObject<WorkerDto>(workersResponse);
                
                return View(worker);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            using (var client = new HttpClient())
            {
                //Workers
                var workersUrl = $"{baseUrl}api/workers/{id}";
                var workersResponse = await client.GetStringAsync(workersUrl);
                var worker = JsonConvert.DeserializeObject<WorkerDto>(workersResponse);

                //Projects
                var projects = deserializeProjectDtos(client);
                ViewBag.Projects = new SelectList(projects.Result, "ProjectId", "Name", worker.Project.ProjectId);

                //Assignments
                var assignments
                    = deserializeAssignmentDtos(client);
                ViewBag.Assignments = new MultiSelectList(assignments.Result, "AssignmentId", "Title",worker.Assignments.Select(x=>x.AssignmentId));

                //Roles
                var roles=deserializeRoleDtos(client);
                ViewBag.Roles = new SelectList(roles.Result, "RoleId", "Name", worker.Role.RoleId);
                
                return View(worker);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(WorkerDto workerDto)
        {
            
            using (var client = new HttpClient())
            {
                //var projects=deserializeProjectDtos(client);
                //var roles = deserializeRoleDtos(client);
                //var assignments = deserializeAssignmentDtos(client);

                //var projId = workerDto.Project.ProjectId;
                //workerDto.Project = projects.Result.SingleOrDefault(x => x.ProjectId == projId);

                //var roleId = workerDto.Role.RoleId;
                //workerDto.Role = roles.Result.SingleOrDefault(x => x.RoleId == roleId);
                
                //workerDto.Assignments = null;
                //if (workerDto.AssignmentsId!=null)
                //{
                //    workerDto.Assignments=new List<AssignmentDto>();
                //    foreach (var id in workerDto.AssignmentsId)
                //    {
                //        var assignment = assignments.Result.FirstOrDefault(x => x.AssignmentId== id);
                //        workerDto.Assignments.Add(assignment);
                //    }
                //}

                var workersUrl = $"{baseUrl}api/workers/{workerDto.WorkerId}";
                var workerDtoString = JsonConvert.SerializeObject(workerDto);
                var workersResponse = await client.PutAsync(workersUrl,
                    new StringContent(workerDtoString, Encoding.UTF8, "application/json"));

                if (workersResponse.IsSuccessStatusCode)
                {
                    workerDto =
                        JsonConvert.DeserializeObject<WorkerDto>(
                            await workersResponse.Content.ReadAsStringAsync());
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Update failed");
                }

                return RedirectToAction("Index",Index());
            }
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            using (var client = new HttpClient())
            {
                //Roles
                var roles = deserializeRoleDtos(client);
                ViewBag.Roles = new SelectList(roles.Result, "RoleId", "Name");

                //Projects
                var projects = deserializeProjectDtos(client);
                ViewBag.Projects = new SelectList(projects.Result, "ProjectId", "Name");

                return View(new WorkerDto());
            }
        }

        [HttpPost]
        public async Task<IActionResult> Create(WorkerDto workerDto)
        {
            using (var client = new HttpClient())
            {
                var workerUrl = $"{baseUrl}api/workers/";
                var workerDtoString = JsonConvert.SerializeObject(workerDto);
                var workerResponse = await client.PostAsync(workerUrl,
                    new StringContent(workerDtoString, Encoding.UTF8, "application/json"));
                if (workerResponse.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index", Index());
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Update failed");
                    return View(workerDto);
                }
            }
        }

        private async Task<List<ProjectDto>> deserializeProjectDtos(HttpClient client)
        {
            var projectsUrl = $"{baseUrl}api/projects";
            var projectsResponse = await client.GetStringAsync(projectsUrl);
            var projects = JsonConvert.DeserializeObject<List<ProjectDto>>(projectsResponse);
            return projects;
        }

        private async Task<List<RoleDto>> deserializeRoleDtos(HttpClient client)
        {
            var rolesUrl = $"{baseUrl}api/roles";
            var rolesResponse = await client.GetStringAsync(rolesUrl);
            var roles = JsonConvert.DeserializeObject<List<RoleDto>>(rolesResponse);
            return roles;
        }

        private async Task<List<AssignmentDto>> deserializeAssignmentDtos(HttpClient client)
        {
            var assignmentsUrl = $"{baseUrl}api/assignments";
            var assignmentsResponse = await client.GetStringAsync(assignmentsUrl);
            var assignments = JsonConvert.DeserializeObject<List<AssignmentDto>>(assignmentsResponse);
            return assignments;
        }
    }
}

Task.Manager/Task.Manager.WebAdmin/Views/Assignments/Create.cshtml
@model AssignmentDto
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<form asp-action="Create" method="post" enctype="multipart/form-data">
    @Html.AntiForgeryToken()

    <div class="form-group">
        <label asp-for="Title">
        </label>
        <input asp-for="Title" class="form-control" />
    </div>     <div class="form-group">
        <label asp-for="Description"></label>
        <textarea asp-for="Description" class="form-control"></textarea>
    </div>
    <div class="form-group">
        <label asp-for="Status"></label>
        <select asp-for="Status" class="form-control">
            <option>Active</option>
            <option>Inactive</option>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="ProjectId">Project </label><select asp-for="ProjectId"
                                                       asp-items="ViewBag.Projects" class="form-control">
            <option></option>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="WorkerId">Worker</label> <select asp-for="WorkerId"
                                                     asp-items="ViewBag.Workers" class="form-control">
            <option></option>
        </select>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
</form>

Task.Manager/Task.Manager.WebAdmin/Views/Assignments/Edit.cshtml
@model AssignmentDto
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<form asp-action="Edit" method="post" enctype="multipart/form-data">
    @Html.AntiForgeryToken()     <input type="hidden" asp-for="AssignmentId" />

    <div class="form-group">
        <label asp-for="Title">
        </label>
        <input asp-for="Title" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Description"></label>
        <textarea asp-for="Description" class="form-control"></textarea>
    </div>
    <div class="form-group">
        <label asp-for="Status"></label>
        <select asp-for="Status" class="form-control">
            <option>Active</option>
            <option>Inactive</option>
            <option>Completed</option>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="WorkerId"></label>Worker <select asp-for="WorkerId"
                                                         asp-items="ViewBag.Workers" class="form-control">
            <option></option>
        </select>
    </div>
    <div style="display: none;" class="form-group">
        <label asp-for="ProjectId" type="hidden"></label>
        <select type="hidden" asp-for="ProjectId" asp-items="ViewBag.Projects" multiple class="form-control"></select>
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>

Task.Manager/Task.Manager.WebAdmin/Views/Assignments/Get.cshtml
@model AssignmentDto
@{
    ViewData["Title"] = "Get";
}

<h1 style="text-align: center">Assignment</h1>

<html>
<head>
    <style>
        textarea {
            width: 800px;
            height: 150px;
        }
        div.editable {
            width: 800px;
            height: 200px;
            border: 1px solid #ccc;
            padding: 5px;
        }

        strong {
            font-weight: bold;
        }
    </style>
</head>
<body>
<a style="float:right" class="btn btn-info" asp-action="Edit" asp-route-id="@Model.AssignmentId" asp-route-projectId="@Model.ProjectId" >Edit assignment</a>
<h2 style="text-align: left">Name: @Model.Title</h2>

<div class="row book-panel">
    <div class="col-sm-6">
        @if (@Model.Worker!=null)
        {
            <p>Worker: <a asp-action="Get" asp-controller="Workers" asp-route-id="@Model.Worker.WorkerId">@Model.Worker.Name</a></p>
        }
        else
        {
            <p>Worker: Not assigned</p>
        }
        <p>Project: <a asp-action="Get" asp-controller="Projects" asp-route-id="@Model.Project.ProjectId">@Model.Project.Name</a></p>
        <p>Status: @Model.Status</p>
    </div>
    
</div>
@if (Model.Status == "Active")
{
    <div class="row">
        <div class="col-sm-6">
            <h2 style="text-align: left">Comments:</h2>
            @foreach (var g in Model.Comments)
            {
                <p></p>
                <form action="#" method="post">
                    <div contenteditable="false" style="color: black; ">
                        <br><span >By: @g.Worker.Name</span>
                        <br />
                        <br>@g.Description
                        <br>
                        <br/><span style="text-align: right; color: black">@g.AddedOn</span>
                    </div>
                    <a style="float:left" class="btn btn-primary" asp-controller="Comments" asp-action="Edit" asp-route-id="@g.CommentId"asp-route-assignmentId="@Model.AssignmentId" asp-route-workerId="@Model.WorkerId">Edit</a>
                    <a style="float:left" class="btn btn-primary" asp-controller="Comments" asp-action="Delete" asp-route-id="@g.CommentId" >Delete</a>
                </form>
                <hr style="width:50%;text-align:left;margin-left:0">
            }

        </div>
    </div>
    <p></p>
    <a style="float:left" class="btn btn-primary" asp-controller="Comments" asp-action="Create" asp-route-assignmentId="@Model.AssignmentId" asp-route-workerId="@Model.WorkerId" asp-route-projectId="@Model.ProjectId">Add comment</a>
}

</body>
</html>

Task.Manager/Task.Manager.WebAdmin/Views/Assignments/Index.cshtml
@model List<AssignmentDto>
@{
    ViewData["Title"] = "Assignments";
}

<html>
<head>
    <style>

    </style>
</head>

<body>
<h1>@ViewData["Title"]</h1>

<table class="table table-bordered table-striped table-hover">
    <thead>
    <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Status</th>
        <th>Project</th>
        <th>Worker</th>
        <th>Created On</th>
        <th>Updated On</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var assignment in Model)
    {
        <tr>
            <td>@assignment.Title</td>
            <td><a asp-action="Get" asp-route-id="@assignment.AssignmentId">@assignment.Title</a></td>
            <td>@assignment.Status</td>
            <td>@assignment.Project.Name</td>
            <td>
                <a href="#" class="worker-name">@assignment.Project.Description</a>
            </td>
            <td>@assignment.CreatedOn</td>
            <td>@assignment.UpdatedOn</td>
            <td>
                <a asp-action="Edit" asp-route-id="@assignment.AssignmentId" class="btn btn-success">
                    <i class="glyphicon glyphicon-edit"></i>
                </a>
            </td>
        </tr>

    }
    </tbody>
</table>
</body>
</html>