Task.Manager/Task.Manager.WebAdmin/Controllers/AssignmentsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using Task.Manager.DTO;
using Task.Manager.Entities;

namespace Task.Manager.AdminWeb.Controllers
{
    public class AssignmentsController : Controller
    {
        private string baseUrl = "https://localhost:44358/";
        
        public async Task<IActionResult> Index()
        {
            using (var client = new HttpClient())
            {
                var assignmentsUrl = $"{baseUrl}api/assignments";
                var assignmentsResponse = await client.GetStringAsync(assignmentsUrl);

                var assignments = JsonConvert.DeserializeObject<List<AssignmentDto>>(assignmentsResponse);

                return View(assignments);
            }
        }

        public async Task<IActionResult> Get(int id)
        {
            using (var client=new HttpClient())
            {
                var assignmentsUrl = $"{baseUrl}api/assignments/{id}";
                var assignmentsResponse = await client.GetStringAsync(assignmentsUrl);

                var assignments = JsonConvert.DeserializeObject<AssignmentDto>(assignmentsResponse);

                return View(assignments);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id,int projectId)
        {
            using (var client = new HttpClient())
            {
                //Assignment
                var assignmentsUrl = $"{baseUrl}api/assignments/{id}";
                var assignmentsResponse = await client.GetStringAsync(assignmentsUrl);
                var assignment = JsonConvert.DeserializeObject<AssignmentDto>(assignmentsResponse);
                
                //Projects
                var projects = deserializeProjectDto(client);
                var project = new List<ProjectDto>();
                project.Add(projects.Result.FirstOrDefault(x=>x.ProjectId== projectId));
                ViewBag.Projects = new SelectList(project, "ProjectId", "Name");

                //Workers
                var workers = deserializeWorkerDtos(client);
                var worker = new List<WorkerDto>();
                worker.AddRange(project[0].Workers);
                ViewBag.Workers = new SelectList(worker, "WorkerId", "Name");

                return View(assignment);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(AssignmentDto assignmentDto)
        {
            using (var client = new HttpClient())
            {
                if (assignmentDto.Status=="Inactive" || assignmentDto.Status == "Completed")
                {
                    assignmentDto.WorkerId = null;
                }
                var assignmentsUrl = $"{baseUrl}api/assignments/{assignmentDto.AssignmentId}";
                var assignmentDtoString = JsonConvert.SerializeObject(assignmentDto);
                var assignmentsResponse = await client.PutAsync(assignmentsUrl, new StringContent(assignmentDtoString,Encoding.UTF8, "application/json"));

                if (assignmentsResponse.IsSuccessStatusCode)
                {
                    assignmentDto =
                        JsonConvert.DeserializeObject<AssignmentDto>(
                            await assignmentsResponse.Content.ReadAsStringAsync());
                }
                else
                {
                    ModelState.AddModelError(string.Empty,"Update failed");
                }
               
                return RedirectToAction("Index","Projects");
            }
        }

        [HttpGet]
        public async Task<IActionResult> Create(int id)
        {
            using (var client = new HttpClient())
            {
                var projects = deserializeProjectDto(client);
                var project = new List<ProjectDto>(projects.Result);
                ViewBag.Projects = new SelectList(project,"ProjectId","Name");
                var workers = new List<WorkerDto>();
                workers.AddRange(project[0].Workers);
                ViewBag.Workers = new SelectList(workers, "WorkerId", "Name");
                return View(new AssignmentDto());
            }
        }

        [HttpPost]
        //POST: Assignment
        public async Task<IActionResult> Create(AssignmentDto assignmentDto)
        {
            using (var client = new HttpClient())
            {
                if (assignmentDto.WorkerId==0)
                {
                    assignmentDto.WorkerId = null;
                }
                var assignmentUrl = $"{baseUrl}api/assignments/";
                var assignmentDtoString = JsonConvert.SerializeObject(assignmentDto);
                var assignmentResponse = await client.PostAsync(assignmentUrl,
                    new StringContent(assignmentDtoString, Encoding.UTF8, "application/json"));
                if (assignmentResponse.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index", "Projects");

                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Update failed");
                    return View(assignmentDto);
                }
            }
        }

        private async Task<List<ProjectDto>> deserializeProjectDto(HttpClient client)
        {
            var projectsUrl = $"{baseUrl}api/projects/";
            var projectsResponse = await client.GetStringAsync(projectsUrl);
            var projects = JsonConvert.DeserializeObject<List<ProjectDto>>(projectsResponse);
           
            return projects;
        }

        private async Task<List<WorkerDto>> deserializeWorkerDtos(HttpClient client)
        {
            var workersUrl = $"{baseUrl}api/workers";
            var workersResponse = await client.GetStringAsync(workersUrl);
            var workers = JsonConvert.DeserializeObject<List<WorkerDto>>(workersResponse);

            return workers;
        }
    }
}

Task.Manager/Task.Manager.WebAdmin/Controllers/WorkersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using Task.Manager.DTO;
using Task.Manager.Entities;

namespace Task.Manager.WebAdmin.Controllers
{
    public class WorkersController : Controller
    {
        private string baseUrl = "https://localhost:44358/";

        public async Task<IActionResult> Index()
        {
            using (var client = new HttpClient())
            {
                var workersUrl = $"{baseUrl}api/workers";
                var workersResponse = await client.GetStringAsync(workersUrl);

                var workers = JsonConvert.DeserializeObject<List<WorkerDto>>(workersResponse);

                return View(workers);
            }
        }

        public async Task<IActionResult> Get(int id)
        {
            using (var client = new HttpClient())
            {
                //Workers
                var workersUrl = $"{baseUrl}api/workers/{id}";
                var workersResponse = await client.GetStringAsync(workersUrl);
                var worker = JsonConvert.DeserializeObject<WorkerDto>(workersResponse);
                
                return View(worker);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            using (var client = new HttpClient())
            {
                //Workers
                var workersUrl = $"{baseUrl}api/workers/{id}";
                var workersResponse = await client.GetStringAsync(workersUrl);
                var worker = JsonConvert.DeserializeObject<WorkerDto>(workersResponse);

                //Projects
                var projects = deserializeProjectDtos(client);
                ViewBag.Projects = new SelectList(projects.Result, "ProjectId", "Name", worker.Project.ProjectId);

                //Assignments
                var assignments
                    = deserializeAssignmentDtos(client);
                ViewBag.Assignments = new MultiSelectList(assignments.Result, "AssignmentId", "Title",worker.Assignments.Select(x=>x.AssignmentId));

                //Roles
                var roles=deserializeRoleDtos(client);
                ViewBag.Roles = new SelectList(roles.Result, "RoleId", "Name", worker.Role.RoleId);
                
                return View(worker);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(WorkerDto workerDto)
        {
            
            using (var client = new HttpClient())
            {
                //var projects=deserializeProjectDtos(client);
                //var roles = deserializeRoleDtos(client);
                //var assignments = deserializeAssignmentDtos(client);

                //var projId = workerDto.Project.ProjectId;
                //workerDto.Project = projects.Result.SingleOrDefault(x => x.ProjectId == projId);

                //var roleId = workerDto.Role.RoleId;
                //workerDto.Role = roles.Result.SingleOrDefault(x => x.RoleId == roleId);
                
                //workerDto.Assignments = null;
                //if (workerDto.AssignmentsId!=null)
                //{
                //    workerDto.Assignments=new List<AssignmentDto>();
                //    foreach (var id in workerDto.AssignmentsId)
                //    {
                //        var assignment = assignments.Result.FirstOrDefault(x => x.AssignmentId== id);
                //        workerDto.Assignments.Add(assignment);
                //    }
                //}

                var workersUrl = $"{baseUrl}api/workers/{workerDto.WorkerId}";
                var workerDtoString = JsonConvert.SerializeObject(workerDto);
                var workersResponse = await client.PutAsync(workersUrl,
                    new StringContent(workerDtoString, Encoding.UTF8, "application/json"));

                if (workersResponse.IsSuccessStatusCode)
                {
                    workerDto =
                        JsonConvert.DeserializeObject<WorkerDto>(
                            await workersResponse.Content.ReadAsStringAsync());
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Update failed");
                }

                return RedirectToAction("Index",Index());
            }
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            using (var client = new HttpClient())
            {
                //Roles
                var roles = deserializeRoleDtos(client);
                ViewBag.Roles = new SelectList(roles.Result, "RoleId", "Name");

                //Projects
                var projects = deserializeProjectDtos(client);
                ViewBag.Projects = new SelectList(projects.Result, "ProjectId", "Name");

                return View(new WorkerDto());
            }
        }

        [HttpPost]
        public async Task<IActionResult> Create(WorkerDto workerDto)
        {
            using (var client = new HttpClient())
            {
                var workerUrl = $"{baseUrl}api/workers/";
                var workerDtoString = JsonConvert.SerializeObject(workerDto);
                var workerResponse = await client.PostAsync(workerUrl,
                    new StringContent(workerDtoString, Encoding.UTF8, "application/json"));
                if (workerResponse.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index", Index());
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Update failed");
                    return View(workerDto);
                }
            }
        }

        private async Task<List<ProjectDto>> deserializeProjectDtos(HttpClient client)
        {
            var projectsUrl = $"{baseUrl}api/projects";
            var projectsResponse = await client.GetStringAsync(projectsUrl);
            var projects = JsonConvert.DeserializeObject<List<ProjectDto>>(projectsResponse);
            return projects;
        }

        private async Task<List<RoleDto>> deserializeRoleDtos(HttpClient client)
        {
            var rolesUrl = $"{baseUrl}api/roles";
            var rolesResponse = await client.GetStringAsync(rolesUrl);
            var roles = JsonConvert.DeserializeObject<List<RoleDto>>(rolesResponse);
            return roles;
        }

        private async Task<List<AssignmentDto>> deserializeAssignmentDtos(HttpClient client)
        {
            var assignmentsUrl = $"{baseUrl}api/assignments";
            var assignmentsResponse = await client.GetStringAsync(assignmentsUrl);
            var assignments = JsonConvert.DeserializeObject<List<AssignmentDto>>(assignmentsResponse);
            return assignments;
        }
    }
}

Task.Manager/Task.Manager.WebAdmin/Views/Projects/Create.cshtml
@model ProjectDto
@{
    ViewData["Title"] = "Create";
}

<h1>@ViewData["Title"]</h1>

<form asp-action="Create" method="post" enctype="multipart/form-data">
    @Html.AntiForgeryToken()   

    <div class="form-group">
        <label asp-for="Name">
        </label>
        <input asp-for="Name" class="form-control" />
    </div>     <div class="form-group">
        <label asp-for="Description"></label>
        <textarea asp-for="Description" class="form-control"></textarea>
    </div>     <div class="form-group">
    <button type="submit" class="btn btn-primary">Save</button>
    </div>
</form>

Task.Manager/Task.Manager.WebAdmin/Views/Projects/Edit.cshtml
@model ProjectDto
@{
    ViewData["Title"] = "Edit";
}

<h1>@ViewData["Title"]</h1>

<form asp-action="Edit" method="post" enctype="multipart/form-data">
    @Html.AntiForgeryToken()     <input type="hidden" asp-for="ProjectId" />

    <div class="form-group">
        <label asp-for="Name">
        </label>
        <input asp-for="Name" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Description"></label>
        <textarea asp-for="Description" class="form-control"></textarea>
    </div>
    <div class="form-group">
        <label asp-for="Status">
        </label>
        <input asp-for="Status" class="form-control" />
    </div>
    <div style="display: none;" class="form-group">
        <label asp-for="AssignmentIds" type="hidden"></label>
        <select type="hidden" asp-for="AssignmentIds" asp-items="ViewBag.Assignments" multiple class="form-control"></select>
    </div>
    <div style="display: none;" class="form-group">
        <label asp-for="WorkerIds" type="hidden"></label>
        <select type="hidden" asp-for="WorkerIds" asp-items="ViewBag.Workers" multiple class="form-control"></select>
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>

Task.Manager/Task.Manager.WebAdmin/Views/Projects/Get.cshtml
@using Microsoft.CodeAnalysis.CSharp.Syntax
@model ProjectDto
@{
    ViewData["Title"] = "Get";
}
<html>
<head>

</head>
<body>
    <h1 style="text-align: center">@Model.Name</h1>

    <div class="form-group shadow-textarea">
        <h2>Description</h2>
        <textarea class="form-control z-depth-1" id="exampleFormControlTextarea6" rows="3" disabled>@Model.Description</textarea>
    </div>
    <br/>
    <h2>Workers</h2>
    <table class="table table-bordered table-striped table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Role</th>
                <th>Tasks</th>
            </tr>
        </thead>
        <tbody id="myTable">
            @foreach (var worker in Model.Workers.Where(x => x.Status == "Active"))
            {
                <tr>
                    <td><a asp-controller="Workers" asp-action="Get" asp-route-id="@worker.WorkerId">@worker.Name</a></td>
                    <td>@worker.Email</td>
                    <td>@worker.Role.Name</td>
                    <td>
                        @foreach (var g in worker.Assignments)
                        {
                            <a class="badge badge-primary" asp-controller="Assignments" asp-action="Get" asp-route-id="@g.AssignmentId">@g.Title</a>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <br/>
    <h2>Unassigned tasks</h2>
    <table class="table table-bordered table-striped table-hover">
        <thead>
            <tr>
                <th>Title</th>
                <th>Description</th>
                <th>Worker</th>
            </tr>
        </thead>
        <tbody>

            @foreach (var assignment in Model.Assignments.Where(x => x.Status == "Inactive"))
            {
                <tr>
                    <td><a asp-controller="Assignments" asp-action="Get" asp-route-id="@assignment.AssignmentId">@assignment.Title</a></td>
                    <td>@assignment.Description</td>
                    @if (assignment.Worker != null)
                    {
                        <td><a asp-controller="Workers" asp-action="Get" asp-route-id="@assignment.Worker.WorkerId">@assignment.Worker.Name</a></td>
                    }
                    else
                    {
                        <td>No worker assigned</td>
                    }

                </tr>
            }
        </tbody>
    </table>

    <a style="float:right" class="btn btn-info" asp-controller="Assignments" asp-action="Create" asp-route-id="@Model.ProjectId">Create task</a>
</body>
</html>

Task.Manager/Task.Manager.WebAdmin/Views/Projects/Index.cshtml
@model List<ProjectDto>
@{
    ViewData["Title"] = "Projects";
}


<html>
<head>
    <h1>@ViewData["Title"]</h1>
</head>
<body>
<table class="table table-bordered table-striped table-hover">
    <thead>
    <tr>
        <th>Name</th>
        <th>Description</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var projects in Model.Where(x=>x.Status=="Active"))
    {
        <tr>
            <td><a asp-action="Get" asp-route-id="@projects.ProjectId">@projects.Name</a></td>
            <td>@projects.Description</td>
        </tr>
    }
    <a style="float:right" class="btn btn-info" asp-action="Create" >Create new project</a>
    </tbody>
</table>
</body>
</html>